output_model_name: lewm
subdir: lewm-koch-20260331-143533
num_workers: 6
train_split: 0.9
seed: 3072
img_size: 224
patch_size: 14
encoder_scale: tiny
dump_object: true
trainer:
  max_epochs: 100
  devices: auto
  accelerator: gpu
  precision: bf16
  gradient_clip_val: 1.0
loader:
  batch_size: 128
  num_workers: 6
  persistent_workers: true
  prefetch_factor: 3
  pin_memory: true
optimizer:
  type: AdamW
  lr: 5.0e-05
  weight_decay: 0.001
wandb:
  enabled: true
  config:
    entity: pauwelstanguy-pha-sto
    project: le-wm-koch
    name: lewm-runpod-run-1
    id: lewm-koch-20260331-143533
    resume: allow
    log_model: false
wm:
  type: lewm
  history_size: 3
  num_preds: 1
  embed_dim: 192
  action_dim: 6
  proprio_dim: 6
  state_dim: 6
predictor:
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0
loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
data:
  dataset:
    num_steps: ${eval:'${wm.num_preds} + ${wm.history_size}'}
    frameskip: 5
    name: train__observation_images_laptop
    keys_to_load:
    - pixels
    - action
    - proprio
    - state
    keys_to_cache:
    - action
    - proprio
    - state
